### ISSUE TITLE
CCDT Support

### ISSUE THREAD

**Issue by orweinberger** [mqlight/nodejs-mqlight#10]
I would like to connect to an MQ via CCDT configuration file. Is this somehow supported by this module?

**Comment by dnwe** [comment]
Hi @orweinberger, no this isn't something that is currently supported by the nodejs module. I don't believe that traditional IBM MQ supports output of CCDT files for AMQP channels does it?

**Comment by dnwe** [comment]
@orweinberger assume that you're happy to close this? If you haven't yet determined if IBM MQ supports output of CCDT files for AMQP channels, I'd suggest that you post over on dW answers [here](https://developer.ibm.com/answers/topics/mq/) with the MQ tag to query it
