### ISSUE TITLE
Set Properties ReplyToQ and ReplyToQmgr

### ISSUE THREAD

**Issue by MPBatista** [mqlight/nodejs-mqlight#13]
Hi,

We have to send a message to the IBM MQ 8 in zOS, for that we create an instance of the IBM MQ 8.0.0.5 with the topics that send over the remote queue to the mainframe.

But in the mainframe side, we can't send, or capture, the properties ReplyToQ and ReplyToQmgr.

Have you an idea of how to set this information in the headers ou in the options/properties?

Regards.

**Comment by dnwe** [comment]
Hi @MPBatista and thanks for your question. 

This seems like a broker-specific question, so I'd suggest that you post this over on dW answers [here](https://developer.ibm.com/answers/topics/mq/) with the MQ and zOS tags and an IBM MQ specialist should get back to you with an answer.
