### ISSUE TITLE
nodesecurity.io violation for dependent library

### ISSUE THREAD

**Issue by gavinlharding** [mqlight/nodejs-mqlight#17]
Hi,

We were running an nsp check on our app and mqlight threw up a violation related to its use of moment@2.14.1.

See [https://nodesecurity.io/advisories/532](https://nodesecurity.io/advisories/532)

Is there any possibility to get mqlight patched to use a version >= 2.19.3 of 'moment'?

**Comment by mimaison** [comment]
Thanks for the report! We've updated moment to 2.19.3
