### ISSUE TITLE
How to use options ttl for mqlight.Client.send?

### ISSUE THREAD

**Issue by bttong** [mqlight/nodejs-mqlight#19]
Hello,
I have the following code to send transaction to message hub topic using `ttl` option so that the messages live for the specified time even though there's no consumer subscribes to the topic and when the consumer subscribes later, it will consume these messages and they won't get lost:

producerOpts = {"service":"https://mqlight-lookup-prod02.messagehub.services.us-south.bluemix.net/Lookup?serviceId=xxxx","user":"xxxx","password":"xxxx","qos":1,"ttl":86400000,"id":"test5abeba0"}

producer = MqLight.createClient(producerOpts)
producer.send(topic, message, producerOpts, function (err, topic, data) {
      console.log('Sent: %s ', data)
    })

Am I specifying the `ttl` correct?  Not sure why it's not working for me since the consumer can only see the messages being sent about it subscribes to the topic.

Thanks a lot for your advice.

**Comment by bttong** [comment]
I've learned that `ttl` should be specified for both producer and consumer and consumer should use the same client id.

**Comment by mimaison** [comment]
Thanks @bttong for posting the answer here. Closing now
