### ISSUE TITLE
API not return connection closure reasons.

### ISSUE THREAD

**Issue by ElliotGregory** [mqlight/nodejs-mqlight#2]
When an AMQP server forces an early closure of a connection ,the AMQP message close will contain the reason, for example maximum connections exceeded. However the caller of the Node API only receives
message: NetworkError: CONNECTION ERROR: The remote computer refused the network connection.
and not the reason.

**Comment by dnwe** [comment]
This was already fixed by https://github.com/mqlight/nodejs-mqlight/commit/c7e772806f86309494366280cc066bd1207e53aa / #1
