### ISSUE TITLE
Connect to IBM MQ with Qmgr and Channel (Not AMPQ)

### ISSUE THREAD

**Issue by srPuebla** [mqlight/nodejs-mqlight#51]
Hi,

I have the next parameters to connect to 

Hostname: 192.168.1.10 
Qmgr: COMMR01
Port: 1414
Channel: AUTOCHAN
Quee: AUTO.IN

However, i am using Mqlight libraries. Python, nodejs and i dont know if is posible to connect to that kind of Quees, cause i only see examples with amqp. Could you help me to make an example to connect to with that Quee? I can use nodejs-mqlight or python-mqlight

Please, i need help.

Regards.

**Comment by srPuebla** [comment]
Comment Extra:
Typical client connection

var client = mqlight.createClient({service: 'amqp://localhost:5672'});

I dont want this... i want to connect to 

Hostname: 192.168.1.10
Qmgr: COMMR01
Port: 1414
Channel: AUTOCHAN
Quee: AUTO.IN

**Comment by dnwe** [comment]
@srPuebla yes this mqlight module is only usable for connecting over the amqp-based protocol to MQ in a pubsub deployment. I think you might be looking for the https://github.com/ibm-messaging/mq-mqi-nodejs module — see https://developer.ibm.com/messaging/2018/06/05/easier-use-nodejs-interface-mq/ for background.
