### ISSUE TITLE
There is mechanism for durable subscription in mqlight ?

### ISSUE THREAD

**Issue by adhasyuhada** [mqlight/nodejs-mqlight#7]
I want to make subscriber durable subscription with shared subscription, in this mqlight documentation there is no durable subscription using Node JS ?

**Comment by adhasyuhada** [comment]
Hi anybody to help me, if it's not i will to open pmr.

**Comment by arun-c-g** [comment]
Hi  adhasyuhada ,
Did you get any information on this?

regards,
cg

**Comment by adhasyuhada** [comment]
Hi @arun-c-g 
You can add shared string after topic 
recvClient.subscribe('TOPIC,'shared1');

**Comment by dnwe** [comment]
Closing this issue as it seems like the required information is now understood.
